export default {
	"continents": {
		"AF": "Africa",
		"AN": "Antarctica",
		"AS": "Asia",
		"EU": "Europe",
		"NA": "North America",
		"OC": "Oceania",
		"SA": "South America"
	},
	"countries": {
		"full_name": {
			"AD": "Andorra",
			"AE": "United Arab Emirates",
			"AF": "Afghanistan",
			"AG": "Antigua and Barbuda",
			"AI": "Anguilla",
			"AL": "Albania",
			"AM": "Armenia",
			"AO": "Angola",
			"AQ": "Antarctica",
			"AR": "Argentina",
			"AS": "American Samoa",
			"AT": "Austria",
			"AU": "Australia",
			"AW": "Aruba",
			"AX": "Åland Islands",
			"AZ": "Azerbaijan",
			"BA": "Bosnia and Herzegovina",
			"BB": "Barbados",
			"BD": "Bangladesh",
			"BE": "Belgium",
			"BF": "Burkina Faso",
			"BG": "Bulgaria",
			"BH": "Bahrain",
			"BI": "Burundi",
			"BJ": "Benin",
			"BL": "Saint Barthélemy",
			"BM": "Bermuda",
			"BN": "Brunei Darussalam",
			"BO": "Bolivia, Plurinational State of",
			"BQ": "Bonaire, Sint Eustatius and Saba",
			"BR": "Brazil",
			"BS": "Bahamas",
			"BT": "Bhutan",
			"BV": "Bouvet Island",
			"BW": "Botswana",
			"BY": "Belarus",
			"BZ": "Belize",
			"CA": "Canada",
			"CC": "Cocos (Keeling) Islands",
			"CD": "Congo, the Democratic Republic of the",
			"CF": "Central African Republic",
			"CG": "Congo",
			"CH": "Switzerland",
			"CI": "Côte d'Ivoire",
			"CK": "Cook Islands",
			"CL": "Chile",
			"CM": "Cameroon",
			"CN": "China",
			"CO": "Colombia",
			"CR": "Costa Rica",
			"CU": "Cuba",
			"CV": "Cape Verde",
			"CW": "Curaçao",
			"CX": "Christmas Island",
			"CY": "Cyprus",
			"CZ": "Czech Republic",
			"DE": "Germany",
			"DJ": "Djibouti",
			"DK": "Denmark",
			"DM": "Dominica",
			"DO": "Dominican Republic",
			"DZ": "Algeria",
			"EC": "Ecuador",
			"EE": "Estonia",
			"EG": "Egypt",
			"EH": "Western Sahara",
			"EL": "Greece",
			"ER": "Eritrea",
			"ES": "Spain",
			"ET": "Ethiopia",
			"FI": "Finland",
			"FJ": "Fiji",
			"FK": "Falkland Islands (Malvinas)",
			"FM": "Micronesia, Federated States of",
			"FO": "Faroe Islands",
			"FR": "France",
			"GA": "Gabon",
			"GB": "United Kingdom",
			"GD": "Grenada",
			"GE": "Georgia",
			"GF": "French Guiana",
			"GG": "Guernsey",
			"GH": "Ghana",
			"GI": "Gibraltar",
			"GL": "Greenland",
			"GM": "Gambia",
			"GN": "Guinea",
			"GP": "Guadeloupe",
			"GQ": "Equatorial Guinea",
			"GR": "Greece",
			"GS": "South Georgia and the South Sandwich Islands",
			"GT": "Guatemala",
			"GU": "Guam",
			"GW": "Guinea-Bissau",
			"GY": "Guyana",
			"HK": "Hong Kong",
			"HM": "Heard Island and McDonald Islands",
			"HN": "Honduras",
			"HR": "Croatia",
			"HT": "Haiti",
			"HU": "Hungary",
			"ID": "Indonesia",
			"IE": "Ireland",
			"IL": "Israel",
			"IM": "Isle of Man",
			"IN": "India",
			"IO": "British Indian Ocean Territory",
			"IQ": "Iraq",
			"IR": "Iran, Islamic Republic of",
			"IS": "Iceland",
			"IT": "Italy",
			"JE": "Jersey",
			"JM": "Jamaica",
			"JO": "Jordan",
			"JP": "Japan",
			"KE": "Kenya",
			"KG": "Kyrgyzstan",
			"KH": "Cambodia",
			"KI": "Kiribati",
			"KM": "Comoros",
			"KN": "Saint Kitts and Nevis",
			"KP": "Korea, Democratic People's Republic of",
			"KR": "Korea, Republic of",
			"KW": "Kuwait",
			"KY": "Cayman Islands",
			"KZ": "Kazakhstan",
			"LA": "Lao People's Democratic Republic",
			"LB": "Lebanon",
			"LC": "Saint Lucia",
			"LI": "Liechtenstein",
			"LK": "Sri Lanka",
			"LR": "Liberia",
			"LS": "Lesotho",
			"LT": "Lithuania",
			"LU": "Luxembourg",
			"LV": "Latvia",
			"LY": "Libya",
			"MA": "Morocco",
			"MC": "Monaco",
			"MD": "Moldova, Republic of",
			"ME": "Montenegro",
			"MF": "Saint Martin (French part)",
			"MG": "Madagascar",
			"MH": "Marshall Islands",
			"MK": "Macedonia, the Former Yugoslav Republic of",
			"ML": "Mali",
			"MM": "Myanmar",
			"MN": "Mongolia",
			"MO": "Macao",
			"MP": "Northern Mariana Islands",
			"MQ": "Martinique",
			"MR": "Mauritania",
			"MS": "Montserrat",
			"MT": "Malta",
			"MU": "Mauritius",
			"MV": "Maldives",
			"MW": "Malawi",
			"MX": "Mexico",
			"MY": "Malaysia",
			"MZ": "Mozambique",
			"NA": "Namibia",
			"NC": "New Caledonia",
			"NE": "Niger",
			"NF": "Norfolk Island",
			"NG": "Nigeria",
			"NI": "Nicaragua",
			"NL": "Netherlands",
			"NO": "Norway",
			"NP": "Nepal",
			"NR": "Nauru",
			"NU": "Niue",
			"NZ": "New Zealand",
			"OM": "Oman",
			"PA": "Panama",
			"PE": "Peru",
			"PF": "French Polynesia",
			"PG": "Papua New Guinea",
			"PH": "Philippines",
			"PK": "Pakistan",
			"PL": "Poland",
			"PM": "Saint Pierre and Miquelon",
			"PN": "Pitcairn",
			"PR": "Puerto Rico",
			"PS": "Palestine, State of",
			"PT": "Portugal",
			"PW": "Palau",
			"PY": "Paraguay",
			"QA": "Qatar",
			"RE": "Réunion",
			"RO": "Romania",
			"RS": "Serbia",
			"RU": "Russian Federation",
			"RW": "Rwanda",
			"SA": "Saudi Arabia",
			"SB": "Solomon Islands",
			"SC": "Seychelles",
			"SD": "Sudan",
			"SE": "Sweden",
			"SG": "Singapore",
			"SH": "Saint Helena, Ascension and Tristan da Cunha",
			"SI": "Slovenia",
			"SJ": "Svalbard and Jan Mayen",
			"SK": "Slovakia",
			"SL": "Sierra Leone",
			"SM": "San Marino",
			"SN": "Senegal",
			"SO": "Somalia",
			"SR": "Suriname",
			"SS": "South Sudan",
			"ST": "Sao Tome and Principe",
			"SV": "El Salvador",
			"SX": "Sint Maarten (Dutch part)",
			"SY": "Syrian Arab Republic",
			"SZ": "Swaziland",
			"TC": "Turks and Caicos Islands",
			"TD": "Chad",
			"TF": "French Southern Territories",
			"TG": "Togo",
			"TH": "Thailand",
			"TJ": "Tajikistan",
			"TK": "Tokelau",
			"TL": "Timor-Leste",
			"TM": "Turkmenistan",
			"TN": "Tunisia",
			"TO": "Tonga",
			"TR": "Turkey",
			"TT": "Trinidad and Tobago",
			"TV": "Tuvalu",
			"TW": "Taiwan, Province of China",
			"TZ": "Tanzania, United Republic of",
			"UA": "Ukraine",
			"UG": "Uganda",
			"UM": "United States Minor Outlying Islands",
			"US": "United States of America",
			"UY": "Uruguay",
			"UZ": "Uzbekistan",
			"VA": "Holy See (Vatican City State)",
			"VC": "Saint Vincent and the Grenadines",
			"VE": "Venezuela, Bolivarian Republic of",
			"VG": "Virgin Islands, British",
			"VI": "Virgin Islands, U.S.",
			"VN": "Viet Nam",
			"VU": "Vanuatu",
			"WF": "Wallis and Futuna",
			"WS": "Samoa",
			"YE": "Yemen",
			"YT": "Mayotte",
			"ZA": "South Africa",
			"ZM": "Zambia",
			"ZW": "Zimbabwe"
		},
		"alternative_name": {
			"BA": "Bosnia and Herz.",
			"BN": "Brunei",
			"BO": "Bolivia",
			"CF": "Central African Rep.",
			"CD": "Dem. Rep. Congo",
			"CZ": "Czechia",
			"DO": "Dominican Rep.",
			"EH": "W. Sahara",
			"FK": "Falkland Is.",
			"GQ": "Eq. Guinea",
			"IR": "Iran",
			"KP": "North Korea",
			"KR": "South Korea",
			"LA": "Laos",
			"MD": "Moldova",
			"MK": "Macedonia",
			"PS": "Palestine",
			"RU": "Russia",
			"SB": "Solomon Is.",
			"SO": "Somaliland",
			"SS": "S. Sudan",
			"SY": "Syria",
			"SZ": "eSwatini",
			"TF": "Fr. S. Antarctic Lands",
			"TW": "Taiwan",
			"TZ": "Tanzania",
			"US": "United States",
			"VE": "Venezuela",
			"VN": "Vietnam"
		},
		"no_iso_key": [
			"N. Cyprus",
			"Kosovo"
		]
	},
	"states": {
		"AA": "Armed Forces (Americas)",
		"AB": "Alberta",
		"AE": "Armed Forces (Canada, Europe, Middle East)",
		"AK": "Alaska",
		"AL": "Alabama",
		"AP": "Armed Forces (Pacific)",
		"AR": "Arkansas",
		"AS": "American Samoa",
		"AZ": "Arizona",
		"BC": "British Columbia",
		"CA": "California",
		"CO": "Colorado",
		"CT": "Connecticut",
		"DC": "District of Columbia",
		"DE": "Delaware",
		"FL": "Florida",
		"FM": "Federated States of Micronesia",
		"GA": "Georgia",
		"HI": "Hawaii",
		"IA": "Iowa",
		"ID": "Idaho",
		"IL": "Illinois",
		"IN": "Indiana",
		"KS": "Kansas",
		"KY": "Kentucky",
		"LA": "Louisiana",
		"MA": "Massachusetts",
		"MB": "Manitoba",
		"MD": "Maryland",
		"ME": "Maine",
		"MH": "Marshall Islands",
		"MI": "Michigan",
		"MN": "Minnesota",
		"MO": "Missouri",
		"MP": "Northern Mariana Islands",
		"MS": "Mississippi",
		"MT": "Montana",
		"NB": "New Brunswick",
		"NC": "North Carolina",
		"ND": "North Dakota",
		"NE": "Nebraska",
		"NH": "New Hampshire",
		"NJ": "New Jersey",
		"NL": "Newfoundland and Labrador",
		"NM": "New Mexico",
		"NS": "Nova Scotia",
		"NT": "Northwest Territories",
		"NU": "Nunavut",
		"NV": "Nevada",
		"NY": "New York",
		"OH": "Ohio",
		"OK": "Oklahoma",
		"ON": "Ontario",
		"OR": "Oregon",
		"PA": "Pennsylvania",
		"PE": "Prince Edward Island",
		"PR": "Puerto Rico",
		"PW": "Palau",
		"QC": "Quebec",
		"RI": "Rhode Island",
		"SC": "South Carolina",
		"SD": "South Dakota",
		"SK": "Saskatchewan",
		"TN": "Tennessee",
		"TX": "Texas",
		"UT": "Utah",
		"VA": "Virginia",
		"VI": "Virgin Islands",
		"VT": "Vermont",
		"WA": "Washington",
		"WI": "Wisconsin",
		"WV": "West Virginia",
		"WY": "Wyoming",
		"YT": "Yukon"
	}
}
