export const svgXmlns = 'http://www.w3.org/2000/svg';
export const width = 24;
export const height = 24;
export const viewBox = `0 0 24 24`;
export const fill = 'none';
export const stroke = 'currentColor';
export const strokeWidth = 2;
export const strokeLinecap = 'round';
export const strokeLinejoin = 'round';
